version: 0.2
run-as: root
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo We are building flask app
  pre_build:
    commands:
      - docker version
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=621074076471.dkr.ecr.us-east-1.amazonaws.com/my-python-web-apps
      - IMAGE_TAG=latest

  build:
    commands:
      - echo building docker image on date `date`
      - docker build -t flask-demo:latest .
      - docker images
      - docker tag flask-demo:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image into amazon ECR..
      - docker push $REPOSITORY_URI:$IMAGE_TAG
